import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/About.module.css'
import data from '../data/workplace.json'
import { useState } from 'react'
import CardEmployee from '../components/CardEmployee'

const inter = Inter({ subsets: ['latin'] })

console.log(data);
export default function About() {

    const [information, setInformation] = useState([...data])

    return (
        <>
        <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

      <header className={styles.headerstyle}>
        <h1>Finding the Right Mentor for You</h1>
        <p>We want to help you find YOUR mentor.</p>
        <p>By going through the questions below, a more narrowed search will help provide a mentor that is specialized just for your needs!</p>
      </header>


        <div className={styles.grid}>
        <div className={styles.gridlayout}>
        <div>
          <div className={styles.comlay}>
        <h2 className={styles.busdeg}>Computing Mentor: </h2>
        {information && information.map((info, index) => {
          if(info.graduate === "computing") {
            return (
              <div key={index}>
                <CardEmployee role={info.role} colour="#946E83" font="20px"/>
              </div>
            )
          }

        
        })}
       </div>

<div className={styles.buslay}>
        <div>
        <h2 className={styles.busdeg}>Business Mentor: </h2>
        {information && information.map((info, index) => {
          if(info.graduate === "business") {
            return (
              <div key={index}>
                <CardEmployee role={info.role} colour="#605770" font="20px"/>
              </div>
            )
          }

 
})}
</div>
</div>
</div>

<div className={styles.scrolls}>
<Image 
className={styles.scrollone}
width={400}
height={600}
src={'vector/mentor.svg'}
/>
<Image 
className={styles.scrolltwo}
width={400}
height={600}
src={'vector/mentor.svg'}
/>
</div>
</div>
</div>
</main>
</>
    )
}